#!/usr/bin/env bash
#
# demo.sh -- the c001 round trip: generate -> baseline -> validate -> render,
# then the same for every committed dev instance, plus a gallery and the two
# figure SVGs used by the challenge README.
#
# Usage:  bash challenges/c001/demo.sh [OUT_DIR]
#
#   OUT_DIR   where the generated artefacts go.  Default:
#             <repository root>/build/c001-demo   (the directory is created;
#             existing files are overwritten, nothing is ever deleted).
#
# Environment:
#   PYTHON              interpreter command to use, e.g. PYTHON=python3.11 or
#                       PYTHON="uv run python".  Default: "uv run python" when
#                       uv is on PATH, otherwise "python3".
#   C001_DEMO_FIGURES   1 (default) to refresh challenges/c001/demo/*.svg and
#                       demo/demo-6.baseline.json from demo/demo-6.json; 0 to
#                       leave the committed demo/ directory untouched (what the
#                       round-trip test does -- a test must not rewrite files in
#                       the working tree).
#
# Output: progress lines, then the markdown table quoted by the challenge
# README, then the gallery path.  Exit 0 when every layout validated, 1 when
# any did not, 2 on usage errors.
#
# The table is deliberately produced here rather than typed by hand: the
# utilization figures in the README are measurements, not claims.

set -euo pipefail

usage() {
    cat <<'EOF'
usage: bash demo.sh [OUT_DIR]

Runs the challenge c001 round trip:
  1. generate a fresh tier-1 instance (seed 4242, id c001-t1-demo-01)
  2. pack it with the baseline solver
  3. validate the layout (--json)
  4. render it to SVG
  5. baseline + validate every instance in instances/dev, print a markdown
     table of the measured utilizations, and build a gallery
  6. refresh the demo/ figure SVGs when demo/demo-6.json exists

OUT_DIR defaults to <repository root>/build/c001-demo.
Environment: PYTHON, C001_DEMO_FIGURES (see the comments at the top of this file).
EOF
}

case "${1:-}" in
    -h | --help)
        usage
        exit 0
        ;;
esac

if [ "$#" -gt 1 ]; then
    usage >&2
    exit 2
fi

script_dir="$(cd -- "$(dirname -- "$0")" && pwd)"

# Resolve OUT_DIR to an absolute path *before* cd-ing, so that a relative
# argument is interpreted relative to the caller's directory, not this one.
default_out=""
if [ "$#" -eq 1 ] && [ -n "$1" ]; then
    out_dir="$1"
else
    repo_root="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || true)"
    if [ -z "$repo_root" ]; then
        repo_root="$(cd -- "$script_dir/../.." && pwd)"
    fi
    out_dir="$repo_root/build/c001-demo"
    default_out="yes"
fi

mkdir -p -- "$out_dir"
# The default output directory lives inside the repository, so keep the working
# tree clean by making the directory ignore its own contents.  A directory the
# caller named explicitly is left exactly as they left it.
if [ -n "$default_out" ] && [ ! -e "$out_dir/.gitignore" ]; then
    printf '# Generated by challenges/c001/demo.sh; not part of the repository.\n*\n' \
        >"$out_dir/.gitignore"
fi
out_dir="$(cd -- "$out_dir" && pwd)"

cd -- "$script_dir"

# ---------------------------------------------------------------- interpreter
if [ -n "${PYTHON:-}" ]; then
    # Deliberately word-split: PYTHON may be a multi-word command.
    # shellcheck disable=SC2206
    PY=(${PYTHON})
elif command -v uv >/dev/null 2>&1; then
    PY=(uv run python)
else
    PY=(python3)
fi

echo "demo.sh: challenge dir $script_dir"
echo "demo.sh: output dir    $out_dir"
echo "demo.sh: interpreter   ${PY[*]}"
echo

mkdir -p -- "$out_dir/dev"

measures="$out_dir/dev-measures.jsonl"
: >"$measures"

checked=0
failed=0
last_utilization=""

# Run the validator on one (instance, solution) pair.  Appends the tool's JSON
# line to $measures when $3 is "record"; never aborts the script, so one bad
# layout still leaves the remaining rows and the final tally intact.  Leaves the
# measured utilization in $last_utilization (empty when the layout is not valid).
check() {
    local instance="$1" solution="$2" record="${3:-}"
    local out rc=0
    out="$("${PY[@]}" tools/validate.py "$instance" "$solution" --json)" || rc=$?
    checked=$((checked + 1))
    last_utilization="$(printf '%s\n' "$out" |
        sed -n 's/^VALID.*utilization=\([0-9.]*\)%.*$/\1/p' | tail -n 1)"
    if [ -n "$record" ]; then
        printf '%s\n' "$out" | tail -n 1 >>"$measures"
    fi
    if [ "$rc" -ne 0 ]; then
        failed=$((failed + 1))
        echo "demo.sh: NOT VALID: $solution (validate.py exit $rc)" >&2
        printf '%s\n' "$out" >&2
    else
        printf '%s\n' "$out" | sed -n '1p'
    fi
}

# ------------------------------------------------- 1-4: a fresh demo instance
demo_id="c001-t1-demo-01"
demo_instance="$out_dir/$demo_id.json"
demo_solution="$out_dir/$demo_id.solution.json"

echo "[1/6] generate $demo_id (tier 1, seed 4242)"
"${PY[@]}" tools/generate.py --tier 1 --seed 4242 --id "$demo_id" --out "$demo_instance"

echo "[2/6] baseline  $demo_id"
"${PY[@]}" tools/baseline.py "$demo_instance" --out "$demo_solution" --time-budget 60

echo "[3/6] validate  $demo_id"
check "$demo_instance" "$demo_solution"

echo "[4/6] render    $demo_id"
"${PY[@]}" tools/render.py "$demo_instance" "$demo_solution" --out "$out_dir/$demo_id.svg"
echo

# ----------------------------------------------------- 5: the whole dev suite
echo "[5/6] baseline + validate every instance in instances/dev"
for instance in instances/dev/*.json; do
    [ -e "$instance" ] || continue
    id="$(basename "$instance" .json)"
    solution="$out_dir/dev/$id.json"
    "${PY[@]}" tools/baseline.py "$instance" --out "$solution" --time-budget 60 --quiet
    check "$instance" "$solution" record
done
echo

echo "Baseline utilization over the committed dev instances:"
echo
"${PY[@]}" - "$measures" <<'PY'
import json
import sys

rows = []
with open(sys.argv[1], encoding="utf-8") as handle:
    for line in handle:
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except ValueError:
            continue
        measures = obj.get("measures") or {}
        rows.append(
            (
                obj.get("instance_id", "?"),
                measures.get("utilization_pct", obj.get("utilization_pct")),
                measures.get("used_length", obj.get("used_length")),
                bool(obj.get("valid")),
            )
        )

rows.sort(key=lambda row: row[0])
print("| instance | utilization % | used length |")
print("| --- | ---: | ---: |")
for instance_id, utilization, length, valid in rows:
    util = "n/a" if utilization is None else "%.1f" % float(utilization)
    used = "n/a" if length is None else "%.3f" % float(length)
    flag = "" if valid else "  (NOT VALID)"
    print("| %s | %s | %s |%s" % (instance_id, util, used, flag))
PY
echo

gallery="$out_dir/gallery.html"
echo "[6/6] gallery of $out_dir/dev/*.json"
"${PY[@]}" tools/gallery.py "$out_dir/dev" \
    --instances-dir "$script_dir/instances/dev" \
    --out "$gallery"
echo

# ------------------------------------------- the README figures (demo/*.svg)
if [ "${C001_DEMO_FIGURES:-1}" = "0" ]; then
    echo "demo.sh: C001_DEMO_FIGURES=0, leaving demo/ untouched"
elif [ -f demo/demo-6.json ]; then
    echo "demo.sh: refreshing the demo figures from demo/demo-6.json"
    "${PY[@]}" tools/baseline.py demo/demo-6.json \
        --out demo/demo-6.baseline.json --time-budget 60 --quiet
    check demo/demo-6.json demo/demo-6.baseline.json
    figure_baseline="$last_utilization"
    "${PY[@]}" tools/render.py demo/demo-6.json demo/demo-6.baseline.json \
        --out demo/baseline.svg
    if [ -f demo/demo-6.improved.json ]; then
        check demo/demo-6.json demo/demo-6.improved.json
        figure_improved="$last_utilization"
        "${PY[@]}" tools/render.py demo/demo-6.json demo/demo-6.improved.json \
            --out demo/improved.svg
        # The pair is the README's "what good looks like" figure, so the
        # improved layout has to be visibly tighter.  This is a quality warning,
        # not a validity failure: the exit code of this script means "every
        # layout validated", and mixing a judgement into it would blur that.
        if [ -n "$figure_baseline" ] && [ -n "$figure_improved" ]; then
            if awk -v b="$figure_baseline" -v i="$figure_improved" \
                'BEGIN { exit !(i > b) }'; then
                echo "demo.sh: figure utilization ${figure_baseline}% -> ${figure_improved}%"
            else
                echo "demo.sh: WARNING: the improved figure layout is not tighter" >&2
                echo "demo.sh: WARNING: baseline ${figure_baseline}%, improved ${figure_improved}% --" >&2
                echo "demo.sh: WARNING: demo/improved.svg will not illustrate anything" >&2
            fi
        fi
    else
        echo "demo.sh: demo/demo-6.improved.json absent, skipping improved.svg"
    fi
else
    echo "demo.sh: demo/demo-6.json absent, skipping the figure step"
fi
echo

echo "demo.sh: $checked layout(s) validated, $failed failed"
echo "demo.sh: gallery at $gallery"

if [ "$failed" -ne 0 ]; then
    exit 1
fi
